import { createContext, useContext, useCallback, ReactNode } from "react";

const translations: Record<string, string> = {
  // NAV
  "nav.home": "Home",
  "nav.casino": "Casino",
  "nav.leaderboard": "Leaderboard",
  "nav.rewards": "Rewards",
  "nav.connect": "Connect",
  "nav.disconnect": "Disconnect",
  "nav.profile": "Profile",
  "nav.history": "History",
  "nav.wallet": "Wallet",

  // HOME
  "home.solana": "Solana (SOL)",
  "home.live": "LIVE",
  "home.liveOnSolana": "LIVE ON SOLANA",
  "home.heroTitle1": "THE FUTURE OF",
  "home.heroTitle2": "ON-CHAIN GAMING",
  "home.heroDesc": "Play provably fair games, compete with players worldwide and win crypto instantly.",
  "home.balance": "Balance:",
  "home.playNow": "Play Now",
  "home.createAccount": "Create Account",
  "home.volumePlayed": "Volume Played",
  "home.players": "Players",
  "home.games": "Games",
  "home.provablyFair": "Provably Fair",
  "home.ourGames": "OUR GAMES",
  "home.gamesSubtitle": "9 games, provably fair, instant payouts",
  "home.play": "Play",
  "home.howItWorks": "HOW IT WORKS",
  "home.step": "STEP",
  "home.step1Title": "Create your account",
  "home.step1Desc": "Solana wallet generated automatically",
  "home.step2Title": "Pick a game",
  "home.step2Desc": "Blackjack, Mines, Slots, Roulette, Crash, Plinko, Dice, Hi-Lo, Towers",
  "home.step3Title": "Win SOL",
  "home.step3Desc": "Withdraw your winnings instantly",
  "home.fairDesc": "Every game outcome is cryptographically verified on-chain, ensuring complete transparency and fairness. No manipulation possible.",
  "home.learnMore": "Learn more",
  "home.topWins": "TOP WINS",
  "home.viewAll": "View all",
  "home.noWins": "No wins recorded yet",
  "home.readyToPlay": "READY TO PLAY?",
  "home.readyDesc": "Create your account, get your Solana wallet and start winning.",
  "home.ranking": "Ranking",
  "home.footerWarning": "⚠️ PUMPZONE is an experimental platform. Cryptocurrency trading and casino games carry significant risks. Don't gamble more than you can afford to lose. 18+ only.",

  // GAMES
  "game.blackjack": "Blackjack",
  "game.blackjackDesc": "Classic 50/50 with ×2 payout",
  "game.mines": "Mines",
  "game.minesDesc": "Defuse and win big",
  "game.slots": "Slots",
  "game.slotsDesc": "The crypto slot machine",
  "game.roulette": "Roulette",
  "game.rouletteDesc": "Spin the wheel of fate",
  "game.crash": "Crash",
  "game.crashDesc": "Cash out before the crash",
  "game.plinko": "Plinko",
  "game.plinkoDesc": "Drop the ball, hit big multipliers",
  "game.dice": "Dice",
  "game.diceDesc": "Roll over or under your target",
  "game.hilo": "Hi-Lo",
  "game.hiloDesc": "Guess higher or lower",
  "game.towers": "Towers",
  "game.towersDesc": "Climb the tower, cash out before you fall",
  "game.crash.title": "Crash",
  "game.crash.desc": "Cash out before it crashes! The longer you wait, the higher the multiplier.",
  "game.crash.launch": "LAUNCH 🚀",
  "game.crash.cashout": "CASH OUT",
  "game.crash.crashed": "CRASHED",
  "game.crash.cashedOut": "Cashed out",
  "game.crash.history": "Recent Crashes",
  "game.crash.players": "Players",
  "game.crash.nextRound": "Next round...",
  "game.crash.placeBet": "Bet",
  "game.crash.betPlaced": "Bet placed",
  "game.crash.waitingLaunch": "Waiting for launch...",
  "game.crash.nextSoon": "Next round starting soon...",
  "game.crash.betAmount": "Bet Amount",
  "game.crash.autoCashout": "Cashout at",
  "game.crash.profitOnWin": "Profit on Win",
  "game.crash.noPlayers": "No players yet",
  "game.demo": "Demo",
  "game.real": "Real",
  "game.demoMode": "🎮 Demo mode — no real SOL",
  "game.demoBalance": "Demo balance",
  "game.chance": "50% chance · Pays ×2",
  "game.chanceClick": "50% chance · Pays ×2 · Click a tile",
  "game.bet": "Bet",
  "game.won": "Won!",
  "game.lost": "Lost.",
  "game.newGame": "New game",
  "game.deal": "Deal",
  "game.start": "Start",
  "game.spin": "SPIN",
  "game.spinRoulette": "SPIN",
  "game.nothing": "Nothing...",
  "game.dealer": "Dealer",
  "game.you": "You",
  "game.red": "🔴 Red",
  "game.black": "⚫ Black",
  "game.even": "Even",
  "game.odd": "Odd",
  "game.green": "0 Green",

  // CASINO PAGE
  "casino.title": "Casino",
  "casino.subtitle": "Provably fair · Real SOL · Instant payouts",
  "casino.verifyFairness": "Verify Fairness",
  "casino.yourBalance": "Your Balance",
  "casino.gamesAvailable": "Games Available",
  "casino.playersOnline": "Players Online",
  "casino.payout": "Payout",
  "casino.gamesTitle": "Games",
  "casino.recentWins": "Recent Wins",
  "casino.player": "Player",
  "casino.game": "Game",
  "casino.won": "Won",
  "casino.time": "Time",
  "casino.popular": "Popular",
  "casino.hot": "Hot",
  "casino.new": "New",
  "casino.classic": "Classic",
  "casino.beatDealer": "Beat the dealer to 21",
  "casino.avoidMines": "Avoid the mines to win big",
  "casino.matchSymbols": "Match symbols for a payout",
  "casino.pickColor": "Pick your color & spin",
  "casino.cashBeforeCrash": "Cash out before it crashes",
  "casino.dropBall": "Drop the ball, hit big multipliers",
  "casino.rollDice": "Roll over or under your target",
  "casino.guessCard": "Guess if the next card is higher or lower",
  "casino.climbTower": "Climb the tower, cash out before you fall",
  "casino.playWin": "Play & Win SOL",
  "casino.guestDesc": "Provably fair games powered by Solana. Create an account to start playing with real SOL.",
  "casino.getStarted": "Get Started — It's Free",
  "casino.instantPayout": "Instant Payout",
  "casino.encrypted": "Encrypted",
  "casino.sha256": "SHA-256 verified results",
  "casino.directWallet": "Direct to your wallet",
  "casino.aes256": "AES-256 encrypted keys",
  "casino.gambleResponsibly": "🎲 Gamble responsibly — Real SOL on Solana mainnet. 50% win chance, ×2 payout. 18+",

  // LEADERBOARD
  "lb.title": "Leaderboard",
  "lb.subtitle": "Top players ranked by profit",
  "lb.totalPlayers": "Total Players",
  "lb.totalVolume": "Total Volume",
  "lb.gamesToday": "Games Today",
  "lb.avgWinRate": "Avg Win Rate",
  "lb.daily": "Daily",
  "lb.weekly": "Weekly",
  "lb.allTime": "All Time",
  "lb.rank": "Rank",
  "lb.player": "Player",
  "lb.games": "Games",
  "lb.winPct": "Win %",
  "lb.best": "Best",
  "lb.pnl": "PnL",
  "lb.pnlDisplayed": "PnL displayed in SOL",

  // REWARDS
  "rw.title": "Rewards",
  "rw.subtitle": "Complete missions and earn SOL",
  "rw.signIn": "Sign In",
  "rw.signInDesc": "Sign in to access rewards and earn SOL.",
  "rw.rewardsReferrals": "Rewards & Referrals",
  "rw.dailyLogin": "Daily Login Rewards",
  "rw.day": "Day",
  "rw.claim": "Claim",
  "rw.weeklyMissions": "Weekly Missions",
  "rw.play5": "Play 5 games",
  "rw.play5Desc": "Play any 5 casino games",
  "rw.win3": "Win 3 games",
  "rw.win3Desc": "Win 3 games in any mode",
  "rw.wager": "Wager 0.1 SOL",
  "rw.wagerDesc": "Total wagers reach 0.1 SOL",
  "rw.tryAll": "Try all games",
  "rw.tryAllDesc": "Play each game at least once",
  "rw.referral": "Referral Program",
  "rw.referred": "Referred",
  "rw.earnings": "Earnings SOL",
  "rw.commission": "Commission",
  "rw.referralDesc": "Earn 5% commission on every game your referrals play",

  // FAIRNESS
  "fair.title": "Provably Fair",
  "fair.desc": "Every game outcome is cryptographically verified, ensuring complete transparency and fairness. No game can be manipulated — not even by us.",
  "fair.step1": "Server Seed Generated",
  "fair.step1Desc": "Before each game, the server generates a cryptographic seed and commits a SHA-256 hash of it.",
  "fair.step2": "Client Seed Set",
  "fair.step2Desc": "The player provides or accepts a random client seed that will influence the game outcome.",
  "fair.step3": "Combined Hash",
  "fair.step3Desc": "Server seed + Client seed + Nonce are combined and hashed to determine the game result.",
  "fair.step4": "Verify Anytime",
  "fair.step4Desc": "After each game, the server seed is revealed so players can independently verify fairness.",
  "fair.example": "Example Verification",
  "fair.serverSeed": "Server Seed (SHA-256 Hash)",
  "fair.clientSeed": "Client Seed",
  "fair.result": "Result",
  "fair.verify": "Verify a Bet",
  "fair.verifyBtn": "Verify",
  "fair.recentBets": "Your Recent Bets",
  "fair.loadBets": "Load Bets",
  "fair.useInVerifier": "Use in verifier",
  "fair.revealSeed": "Reveal & Verify",
  "fair.algorithm": "Algorithm",

  // PROFILE
  "profile.title": "Profile",
  "profile.signIn": "Sign in to view your profile.",
  "profile.gamesPlayed": "Games Played",
  "profile.winRate": "Win Rate",
  "profile.totalPnl": "Total PnL",
  "profile.biggestWin": "Biggest Win",
  "profile.wallet": "Wallet",
  "profile.solBalance": "SOL Balance",
  "profile.copyAddress": "Copy Address",
  "profile.copied": "Copied",
  "profile.depositWithdraw": "Deposit & Withdraw",
  "profile.deposit": "Deposit (sync on-chain)",
  "profile.syncing": "Syncing...",
  "profile.withdraw": "Withdraw SOL",
  "profile.destAddress": "Destination Solana address",
  "profile.amount": "Amount (SOL)",
  "profile.cancel": "Cancel",
  "profile.send": "Send",
  "profile.sending": "Sending...",
  "profile.gameHistory": "Game History",
  "profile.noGames": "No games played yet",
  "profile.noDeposit": "No SOL available to deposit",
  "profile.invalidAmount": "Invalid amount",
  "profile.invalidAddress": "Invalid address",
  "profile.clientSeed": "Client Seed",
  "profile.clientSeedDesc": "Your client seed is used in the provably fair algorithm. Changing it resets your nonce.",

  // AUTH
  "auth.verification": "📧 Verification",
  "auth.login": "🔑 Sign In",
  "auth.register": "✨ Sign Up",
  "auth.loginTab": "🔑 Sign In",
  "auth.registerTab": "✨ Sign Up",
  "auth.email": "Email",
  "auth.username": "Username",
  "auth.password": "Password",
  "auth.confirmPassword": "Confirm password",
  "auth.signInBtn": "Sign In",
  "auth.createBtn": "Create my account",
  "auth.freeWallet": "🎁 Free Solana address on signup",
  "auth.otpSent": "A verification code has been sent to your email!",
  "auth.enterCode": "Enter the code sent to",
  "auth.6digit": "6-digit code",
  "auth.verify": "Verify",
  "auth.resend": "Resend code",
  "auth.resendIn": "Resend code",
  "auth.back": "← Back",
  "auth.newCodeSent": "New code sent!",
  "auth.passwordMismatch": "Passwords do not match",
  "auth.usernameLength": "Username: 3-20 characters",
  "auth.passwordLength": "Password: 6 characters minimum",
  "auth.error": "An error occurred",
  "auth.invalidCode": "Invalid code",
  "auth.resendError": "Error resending",
  "auth.checkEmail": "Check your email!",
  "auth.clickLink": "Click the confirmation link sent to",
  "auth.checkSpam": "Check your spam folder if you don't see it.",
  "auth.understood": "Got it!",

  // FOOTER
  "footer.desc": "The future of on-chain gaming. Provably fair, instant payouts, powered by Solana.",
  "footer.copyright": "© 2024 PumpZone. All rights reserved. 18+ Gamble responsibly.",

  // NOT FOUND
  "notFound.title": "Page not found",
  "notFound.back": "Go Home",
};

interface LanguageContextType {
  lang: "en";
  setLang: (lang: "en") => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export type Lang = "en";

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const t = useCallback((key: string): string => {
    return translations[key] || key;
  }, []);

  return (
    <LanguageContext.Provider value={{ lang: "en", setLang: () => {}, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be inside LanguageProvider");
  return ctx;
};
