// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgpoqbuqbucdsdbwjmgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxncG9xYnVxYnVjZHNkYndqbWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNzMwMTcsImV4cCI6MjA4ODc0OTAxN30.ryEwFhE_hNwWGY4Bsun1mO-WvOgJMEfsksCjf7K956g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});